kind: Deployment
apiVersion: apps/v1
metadata:
  name: dvwa
spec:
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: public.ecr.aws/f9n2h3p5/dvwapub:<TAG>
        imagePullPolicy: "Always"
  selector:
    matchLabels:
      app: dvwa
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
spec:
  type: LoadBalancer
  selector:
    app: dvwa
  ports:
  - name: http
    port: 8081
    targetPort: 80

scanners: 
  - sast
  - dast
  - secret - sca
  - iac
  - container
dast:
  url: http://XXXXXXXXXXXXXXXX:8081/ 
  fortipentest_scanner: false #true|false 
  full_scan: true #true|false
  
